# Generated by Django 4.2.24 on 2025-09-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioprofile',
            name='degree',
            field=models.CharField(blank=True, help_text='Ex: Licence, Master, Doctorat', max_length=150, null=True),
        ),
    ]
